<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_form_alter(),
 */

function first_module_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id)
{
    if ($form_id = 'user-login-form') {
        $form['#title'] = t('Login with your info');
        $form['name']['#attributes']['placeholder'] = t('Enterr Your Ussername: ');
        $form['pass']['#attributes']['placeholder'] = t('Enterr Your PasswOrd: ');
    }
}

/**
 * Implements hook_preprocess_page(),
 */

function first_module_preprocess_page(&$variables)
{
    $variables['first_module_variable'] = "My first DRP11 Module";
    $variables['hello_world'] = "HELLO WORLD";
}

/**
 * Implements hook_help(),
 */

function first_module_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_match) {
        case 'help.page.first_module':
            $output = "";
            $output .= "<h3>" . t('About') . "</h3>";
            $output .= "<p>" . t('This is an first custom module hook help') . "</p>";
            return $output;
    }
}
